<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ArticleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'string|required|min:3|max:60',
            'author' => 'string|required|min:3|max:60',
            'categories' => 'required|array',
            'full_text' => 'required|string',
        ];
    }

//    public function messages()
//    {
//        return parent::messages(); // TODO: Change the autogenerated stub
//    }
}
